version : '3'
services:
  mysql:
    build: 
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  itop:
    build:
      context: ./itop
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 80:80

volumes:
  db_data : {}